pipelines:
  branches:
    master:
      - step:
          name: Deploy
          script:
            - ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
            - ssh -vvv $SERVER_USER@$SERVER_HOST "echo ok"
