pipelines:
  branches:
    master:
      - step:
          name: Deploy
          script:
            - ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
            - ssh $SERVER_USER@$SERVER_HOST "cd $SERVER_PATH && git pull && docker compose up -d --build"